pos_samps_train: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/uniform/mr_train_plus/0.03/
pos_samps_val: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/uniform/mr_val_plus/0.03/
pos_samps_test: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/uniform/mr_test_plus/0.03/
neg_samps_train: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/uniform/mr_train_minus/0.03/
neg_samps_val: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/uniform/mr_val_minus/0.03/
neg_samps_test: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/uniform/mr_test_minus/0.03/

model: resnet18
pretrained: True
batch_size: 128
epoch: 16

model_save_dir: /media/dontgetdown/model_partition/models/cor_0.03/
retrieve_last_model: False
