pos_samps_train: /home/rsltgy/Documents/caner/datasets/acdc/uniform/mr_train_plus/0.01/
pos_samps_val: /home/rsltgy/Documents/caner/datasets/acdc/uniform/mr_val_plus/0.01/
pos_samps_test: /home/rsltgy/Documents/caner/datasets/acdc/uniform/mr_test_plus/0.01/
neg_samps_train: /home/rsltgy/Documents/caner/datasets/acdc/uniform/mr_train_minus/0.01/
neg_samps_val: /home/rsltgy/Documents/caner/datasets/acdc/uniform/mr_val_minus/0.01/
neg_samps_test: /home/rsltgy/Documents/caner/datasets/acdc/uniform/mr_test_minus/0.01/

model: resnet101
pretrained: True
batch_size: 64
epoch: 16

model_save_dir: /home/rsltgy/Documents/caner/models/cor_0.01/
retrieve_last_model: False
