pos_samps_train: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_train_plus/
pos_samps_val: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_val_plus/
pos_samps_test: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_test_plus/
neg_samps_train: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_train_minus/
neg_samps_val: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_val_minus/
neg_samps_test: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_test_minus/

model: vgg11
pretrained: True
batch_size: 64

model_save_dir: /media/dontgetdown/model_partition/models/
