dataset_name: ACDC
src: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/official_training
format: .nii.gz
process_ones_with: _4d

create_gif: False
show_image: True
show_kspace: True

sigmas: [0.1, 1, 10]
cor_pcs: [0.2]
sampling_type: cartesian

save: False
save_neg: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_train_minus/
save_pos: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_train_plus/

