dataset_name: ACDC
src: /home/rsltgy/Documents/caner/datasets/acdc/official_training
format: .nii.gz
process_ones_with: _4d

create_gif: False
show_image: False
show_kspace: False

sigmas: [1.]
cor_idxes: [0.40, 0.20, 0.15, 0.10, 0.05, 0.03, 0.01]
sampling_type: regular

save: True
save_neg: /home/rsltgy/Documents/caner/datasets/acdc/regular/mr_minus/
save_pos: /home/rsltgy/Documents/caner/datasets/acdc/regular/mr_plus/

