SPLIT:
    train:
        value: 0.7
        plus: 0.5
        minus: 0.5
    val:
        value: 0.2
        plus: 0.5
        minus: 0.5
    test:
        value: 0.1
        plus: 1.0
        minus: 1.0

src: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/official_training
meta_fn: Info.cfg

neg_path: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_minus/
pos_path: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_plus/
