sample_file: dataset/mr_train_1002_image.nii.gz
sample_folder: dataset
dataset_name: ACDC
create_gif: False
show: False
save_to: /media/dontgetdown/model_partition/medical_imaging_datasets/acdc/mr_train_minus/
sigmas: [1.0]
